spring.application.name=employeeFinderByDataForSEO
dataforseo.login=abhishek.2104037@srec.ac.in
dataforseo.password=fb4e0f957730764f
spring.datasource.url=jdbc:mysql://localhost:3306/employee_finder
spring.datasource.username=root
spring.datasource.password=Abishek@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=my-super-secret-key-for-employee-finder-api-2026
jwt.expiration=3600000